version: "3"

services:
    texlive:
        image: ghcr.io/xu-cheng/texlive-full
        volumes:
            - .:/home
        working_dir: /home
        environment:
            - TEXINPUTS
    pandoc:
        image: pandoc/core
        volumes:
            - .:/data
        working_dir: /data
