version: '3'

vars:
  INPUT: '{{.INPUT | default "src/sample/index.tex"}}'
  OUTPUT: '`echo $(basename "$(dirname "{{.INPUT}}")")`'
  DOCKER_COMPOSE: "docker-compose"
  UP: "{{.DOCKER_COMPOSE}} up"
  OUTPUT_DIRECTORY: build
  LATEXMK_ARGS: "-halt-on-error -MP -logfilewarninglist -pdf -shell-escape -interaction=nonstopmode -file-line-error -output-directory={{.OUTPUT_DIRECTORY}}"
  TEXINPUTS: "/home/src//:"
  TEXLIVE_RUN: "{{.DOCKER_COMPOSE}} run -e TEXINPUTS={{.TEXINPUTS}} texlive"
  TEXLIVE_PANDOC: "{{.DOCKER_COMPOSE}} run pandoc"
  LATEXMK_COMMAND: "{{.TEXLIVE_RUN}} latexmk {{.LATEXMK_ARGS}}"

tasks:
  default:
    deps: [fresh]

  build:
    cmds:
      - "{{.LATEXMK_COMMAND}} -jobname={{.OUTPUT}} {{.INPUT}}"
      - task: chmodbuild

  clean:
    cmds:
      - "{{.TEXLIVE_RUN}} rm -rf build"

  chmodbuild:
    cmds:
      - "{{.TEXLIVE_RUN}} chmod 777 build"

  lint:
    cmds:
      - "{{.TEXLIVE_RUN}} chktex {{.INPUT}}"
      - "{{.TEXLIVE_RUN}} lacheck {{.INPUT}}"
      - "{{.TEXLIVE_RUN}} latexindent -s -w {{.INPUT}}"

  fresh:
    deps: [clean, build]

  watch:
    cmds:
      - "{{.LATEXMK_COMMAND}} -pvc -jobname={{.OUTPUT}} {{.INPUT}}"
      - task: chmodbuild
