name: Build

on: [push]

jobs:
  dependencies:
    name: Build dependencies
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.version.outputs.version }}

    steps:
      - name: Check out source files
        uses: actions/checkout@v2

      - name: Create global variables
        id: version
        run: echo "::set-output name=version::$(git rev-parse --short HEAD)"

  build:
    name: Build PDF files
    runs-on: ubuntu-latest
    needs: dependencies
    strategy:
      matrix:
        sources:
          - input: src/cv/index
            output: cv
    steps:
      - name: Check out source files
        uses: actions/checkout@v2

      - name: Create global variables
        id: version
        run: echo "::set-output name=version::$(git rev-parse --short HEAD)"

      - name: Compile document
        uses: xu-cheng/latex-action@v2
        with:
          working_directory: /github/workspace
          root_file: ${{ matrix.sources.input }}.tex
          args: -pdf -file-line-error -halt-on-error -interaction=nonstopmode -output-directory=build -jobname=${{ matrix.sources.output }}
        env:
          TEXINPUTS: "/github/workspace/src//:"

      - name: Upload build assets (${{ matrix.sources.input }})
        uses: actions/upload-artifact@v2
        with:
          name: ${{ matrix.sources.output }}
          path: build/${{ matrix.sources.output }}.pdf

  release:
    name: "Create tag/pre-release"
    runs-on: ubuntu-latest
    needs: [dependencies,build]
    outputs:
      upload_url: ${{ steps.create_release.outputs.upload_url }}
    steps:
      - name: Create pre-release (${{ needs.dependencies.outputs.version }})
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: v${{ github.run_number }}-${{ needs.dependencies.outputs.version }}
          release_name: Version ${{ github.run_number }} (${{ needs.dependencies.outputs.version }})
          draft: true
          prerelease: true

  assets:
    name: Upload release assets
    runs-on: ubuntu-latest
    needs: [dependencies,release]
    strategy:
      matrix:
        assets:
          - input: cv

    steps:
      - name: Download build assets (${{ matrix.assets.input }})
        uses: actions/download-artifact@v2
        with:
          name: ${{ matrix.assets.input }}
          path: ${{ matrix.assets.input }}

      - name: List PDF files
        continue-on-error: true
        run: find . -name \*.pdf -print

      - name: Upload release assets (${{ matrix.assets.input }}, ${{ needs.dependencies.outputs.version }})
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ needs.release.outputs.upload_url }}
          asset_path: ${{ matrix.assets.input }}/${{ matrix.assets.input }}.pdf
          asset_name: ${{ matrix.assets.input }}.pdf
          asset_content_type: application/pdf
